-- Workouts feature: exercise library, assigned/logged workouts, and per-exercise line items.
-- Run once in the Supabase SQL Editor.

-- ============================================================
-- exercises: catalog (seeded library rows + user-added custom rows)
-- ============================================================
create table public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  requires_weight boolean not null default false,
  requires_reps boolean not null default false,
  requires_duration boolean not null default false,
  requires_distance boolean not null default false,
  requires_sets boolean not null default false,
  requires_intensity boolean not null default false,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.exercises enable row level security;

create policy "exercises_select" on public.exercises for select
  using (created_by is null or created_by = auth.uid());

create policy "exercises_insert_own" on public.exercises for insert
  with check (created_by = auth.uid());

-- ============================================================
-- workouts: one row per assigned/logged day for one athlete
-- ============================================================
create table public.workouts (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id),
  assigned_by uuid not null references auth.users(id),
  scheduled_date date not null,
  title text,
  status text not null default 'scheduled' check (status in ('scheduled', 'completed', 'missed')),
  missed_reason text,
  notes text,
  recurrence_group_id text,
  created_at timestamptz not null default now()
);

alter table public.workouts enable row level security;

create policy "workouts_select" on public.workouts for select using (
  exists (select 1 from public.athletes a where a.id = workouts.athlete_id and a.user_id = auth.uid())
  or exists (
    select 1 from public.athlete_access aa
    where aa.athlete_id = workouts.athlete_id
      and aa.granted_to_user_id = auth.uid()
      and aa.status = 'active'
  )
);

create policy "workouts_write" on public.workouts for all using (
  exists (select 1 from public.athletes a where a.id = workouts.athlete_id and a.user_id = auth.uid())
  or exists (
    select 1 from public.athlete_access aa
    where aa.athlete_id = workouts.athlete_id
      and aa.granted_to_user_id = auth.uid()
      and aa.status = 'active'
      and aa.access_level = 'full'
  )
) with check (
  exists (select 1 from public.athletes a where a.id = workouts.athlete_id and a.user_id = auth.uid())
  or exists (
    select 1 from public.athlete_access aa
    where aa.athlete_id = workouts.athlete_id
      and aa.granted_to_user_id = auth.uid()
      and aa.status = 'active'
      and aa.access_level = 'full'
  )
);

-- ============================================================
-- workout_exercises: line items per workout
-- ============================================================
create table public.workout_exercises (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id),
  order_index int not null default 0,
  target_weight numeric,
  target_reps int,
  target_sets int,
  target_duration_seconds int,
  target_distance numeric,
  target_intensity text,
  actual_weight numeric,
  actual_reps int,
  actual_sets int,
  actual_duration_seconds int,
  actual_distance numeric,
  actual_intensity text,
  completed boolean not null default false
);

alter table public.workout_exercises enable row level security;

create policy "workout_exercises_select" on public.workout_exercises for select using (
  exists (
    select 1 from public.workouts w
    join public.athletes a on a.id = w.athlete_id
    where w.id = workout_exercises.workout_id and (
      a.user_id = auth.uid()
      or exists (
        select 1 from public.athlete_access aa
        where aa.athlete_id = a.id
          and aa.granted_to_user_id = auth.uid()
          and aa.status = 'active'
      )
    )
  )
);

create policy "workout_exercises_write" on public.workout_exercises for all using (
  exists (
    select 1 from public.workouts w
    join public.athletes a on a.id = w.athlete_id
    where w.id = workout_exercises.workout_id and (
      a.user_id = auth.uid()
      or exists (
        select 1 from public.athlete_access aa
        where aa.athlete_id = a.id
          and aa.granted_to_user_id = auth.uid()
          and aa.status = 'active'
          and aa.access_level = 'full'
      )
    )
  )
) with check (
  exists (
    select 1 from public.workouts w
    join public.athletes a on a.id = w.athlete_id
    where w.id = workout_exercises.workout_id and (
      a.user_id = auth.uid()
      or exists (
        select 1 from public.athlete_access aa
        where aa.athlete_id = a.id
          and aa.granted_to_user_id = auth.uid()
          and aa.status = 'active'
          and aa.access_level = 'full'
      )
    )
  )
);

-- ============================================================
-- Seed data: 62 exercises from Baseball_Pitcher_Exercise_Library.xlsx
-- ============================================================
insert into public.exercises (name, category, requires_weight, requires_reps, requires_duration, requires_distance, requires_sets, requires_intensity) values
('Goblet Squat', 'Strength', true, true, false, false, true, false),
('Back Squat', 'Strength', true, true, false, false, true, true),
('Front Squat', 'Strength', true, true, false, false, true, true),
('Romanian Deadlift', 'Strength', true, true, false, false, true, false),
('Trap-Bar Deadlift', 'Strength', true, true, false, false, true, true),
('Bulgarian Split Squat', 'Strength', true, true, false, false, true, false),
('Reverse Lunge', 'Strength', true, true, false, false, true, false),
('Lateral Lunge', 'Strength', true, true, false, false, true, false),
('Step-Ups', 'Strength', true, true, false, false, true, false),
('Hip Thrust', 'Strength', true, true, false, false, true, false),
('Glute Bridge', 'Strength', false, true, false, false, true, false),
('Calf Raises', 'Strength', true, true, false, false, true, false),
('Dumbbell Bench Press', 'Strength', true, true, false, false, true, false),
('Incline Dumbbell Press', 'Strength', true, true, false, false, true, false),
('Push-Ups', 'Strength', false, true, false, false, true, false),
('One-Arm DB Row', 'Strength', true, true, false, false, true, false),
('Seated Cable Row', 'Strength', true, true, false, false, true, false),
('Lat Pulldown', 'Strength', true, true, false, false, true, false),
('Pull-Ups', 'Strength', false, true, false, false, true, false),
('Farmer Carry', 'Strength/Core', true, false, true, true, true, false),
('Dead Bug', 'Core', false, true, false, false, true, false),
('Bird Dog', 'Core', false, true, false, false, true, false),
('Plank', 'Core', false, false, true, false, true, false),
('Side Plank', 'Core', false, false, true, false, true, false),
('Pallof Press', 'Core', true, true, false, false, true, false),
('Russian Twist', 'Core', true, true, false, false, true, false),
('Med-Ball Rotational Throw', 'Power', true, true, false, false, true, true),
('Med-Ball Scoop Toss', 'Power', true, true, false, false, true, true),
('Med-Ball Slam', 'Power', true, true, false, false, true, true),
('Box Jump', 'Power', false, true, false, false, true, true),
('Broad Jump', 'Power', false, true, false, true, true, true),
('Lateral Bounds', 'Power', false, true, false, false, true, true),
('Band External Rotation', 'Arm Care', false, true, false, false, true, false),
('Band Internal Rotation', 'Arm Care', false, true, false, false, true, false),
('Band Pull-Aparts', 'Arm Care', false, true, false, false, true, false),
('Band Face Pull', 'Arm Care', false, true, false, false, true, false),
('Band Row', 'Arm Care', false, true, false, false, true, false),
('Scapular Push-Ups', 'Arm Care', false, true, false, false, true, false),
('Wrist Curls', 'Arm Care', true, true, false, false, true, false),
('Reverse Wrist Curls', 'Arm Care', true, true, false, false, true, false),
('Pronation/Supination', 'Arm Care', true, true, false, false, true, false),
('Easy Catch', 'Throwing', false, true, true, true, false, true),
('Long Toss', 'Throwing', false, true, true, true, false, true),
('Flat-Ground Throwing', 'Throwing', false, true, false, true, true, true),
('Bullpen', 'Pitching', false, true, false, false, true, true),
('Pitching Mechanics Drill', 'Pitching', false, true, false, false, true, true),
('Weighted-Ball Throwing', 'Throwing', true, true, false, true, true, true),
('Sprint - 10 yd', 'Speed', false, true, false, true, true, true),
('Sprint - 20 yd', 'Speed', false, true, false, true, true, true),
('Sprint - 30 yd', 'Speed', false, true, false, true, true, true),
('Shuttle Run', 'Conditioning', false, true, true, true, true, true),
('Lateral Shuffle', 'Conditioning', false, true, true, true, true, true),
('Bike', 'Aerobic', false, false, true, true, false, true),
('Jog/Run', 'Aerobic', false, false, true, true, false, true),
('Incline Walk', 'Aerobic', false, false, true, true, false, true),
('Elliptical', 'Aerobic', false, false, true, true, false, true),
('Jump Rope', 'Conditioning', false, true, true, false, true, true),
('Hip Flexor Stretch', 'Mobility', false, false, true, false, true, false),
('Hamstring Stretch', 'Mobility', false, false, true, false, true, false),
('Shoulder Stretch', 'Mobility', false, false, true, false, true, false),
('Thoracic Rotation', 'Mobility', false, true, false, false, true, false),
('World''s Greatest Stretch', 'Mobility', false, true, false, false, true, false);
