-- Game/pitch tracking: extends the existing sessions table for games, adds
-- innings and per-pitch (ball/strike/foul/hbp/hit/out) event logging.
-- Run once in the Supabase SQL Editor.

alter table public.sessions add column game_subtype text; -- 'practice' | 'live', only set when session_type = 'game'
alter table public.sessions add column opponent text;

-- ============================================================
-- innings: one row per inning of a game session, closed out via the
-- End Inning flow (Total Runs required, Earned Runs optional).
-- ============================================================
create table public.innings (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  inning_number int not null,
  total_runs int not null default 0,
  earned_runs int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.innings enable row level security;

create policy "innings_select" on public.innings for select using (
  exists (
    select 1 from public.sessions s
    join public.athletes a on a.id = s.athlete_id
    where s.id = innings.session_id and (
      a.user_id = auth.uid()
      or exists (
        select 1 from public.athlete_access aa
        where aa.athlete_id = a.id and aa.granted_to_user_id = auth.uid() and aa.status = 'active'
      )
    )
  )
);

create policy "innings_write" on public.innings for all using (
  exists (
    select 1 from public.sessions s
    join public.athletes a on a.id = s.athlete_id
    where s.id = innings.session_id and (
      a.user_id = auth.uid()
      or exists (
        select 1 from public.athlete_access aa
        where aa.athlete_id = a.id and aa.granted_to_user_id = auth.uid() and aa.status = 'active' and aa.access_level = 'full'
      )
    )
  )
) with check (
  exists (
    select 1 from public.sessions s
    join public.athletes a on a.id = s.athlete_id
    where s.id = innings.session_id and (
      a.user_id = auth.uid()
      or exists (
        select 1 from public.athlete_access aa
        where aa.athlete_id = a.id and aa.granted_to_user_id = auth.uid() and aa.status = 'active' and aa.access_level = 'full'
      )
    )
  )
);

-- ============================================================
-- game_pitches: one row per pitch/event within an inning. No separate
-- at-bat table - K's, BB's, etc. are derived by replaying this sequence,
-- the same way the bullpen's simulated-batters-faced already works.
-- ============================================================
create table public.game_pitches (
  id bigint generated by default as identity primary key,
  inning_id bigint not null references public.innings(id) on delete cascade,
  outcome text not null check (outcome in ('ball', 'strike', 'foul', 'hbp', 'hit', 'out')),
  pitch_order int not null,
  created_at timestamptz not null default now()
);

alter table public.game_pitches enable row level security;

create policy "game_pitches_select" on public.game_pitches for select using (
  exists (
    select 1 from public.innings i
    join public.sessions s on s.id = i.session_id
    join public.athletes a on a.id = s.athlete_id
    where i.id = game_pitches.inning_id and (
      a.user_id = auth.uid()
      or exists (
        select 1 from public.athlete_access aa
        where aa.athlete_id = a.id and aa.granted_to_user_id = auth.uid() and aa.status = 'active'
      )
    )
  )
);

create policy "game_pitches_write" on public.game_pitches for all using (
  exists (
    select 1 from public.innings i
    join public.sessions s on s.id = i.session_id
    join public.athletes a on a.id = s.athlete_id
    where i.id = game_pitches.inning_id and (
      a.user_id = auth.uid()
      or exists (
        select 1 from public.athlete_access aa
        where aa.athlete_id = a.id and aa.granted_to_user_id = auth.uid() and aa.status = 'active' and aa.access_level = 'full'
      )
    )
  )
) with check (
  exists (
    select 1 from public.innings i
    join public.sessions s on s.id = i.session_id
    join public.athletes a on a.id = s.athlete_id
    where i.id = game_pitches.inning_id and (
      a.user_id = auth.uid()
      or exists (
        select 1 from public.athlete_access aa
        where aa.athlete_id = a.id and aa.granted_to_user_id = auth.uid() and aa.status = 'active' and aa.access_level = 'full'
      )
    )
  )
);
