-- Owner relationship label (Coach/Athlete/Parent), shown next to invited
-- access roles instead of a hardcoded "Owner" tag.
alter table public.athletes add column owner_relationship_label text;

-- ============================================================
-- messages: shared per-athlete thread. Unlike every other write action in
-- this app, BOTH view and full access can post - messaging isn't an editing
-- action, so it isn't gated the way logging/assigning is.
-- ============================================================
create table public.messages (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id),
  sender_id uuid not null references auth.users(id),
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

create policy "messages_select" on public.messages for select using (
  exists (select 1 from public.athletes a where a.id = messages.athlete_id and a.user_id = auth.uid())
  or exists (
    select 1 from public.athlete_access aa
    where aa.athlete_id = messages.athlete_id
      and aa.granted_to_user_id = auth.uid()
      and aa.status = 'active'
  )
);

create policy "messages_insert" on public.messages for insert with check (
  sender_id = auth.uid()
  and (
    exists (select 1 from public.athletes a where a.id = messages.athlete_id and a.user_id = auth.uid())
    or exists (
      select 1 from public.athlete_access aa
      where aa.athlete_id = messages.athlete_id
        and aa.granted_to_user_id = auth.uid()
        and aa.status = 'active'
    )
  )
);

-- Enables live delivery: the Messages screen subscribes to INSERT events on
-- this table while it's open, instead of only refreshing on focus like the
-- rest of the app.
alter publication supabase_realtime add table public.messages;

-- ============================================================
-- message_views: per-user "last viewed" bookmark, mirrors workout_views -
-- powers a separate unread badge for new messages.
-- ============================================================
create table public.message_views (
  user_id uuid not null references auth.users(id),
  athlete_id bigint not null references public.athletes(id),
  last_viewed_at timestamptz not null default now(),
  primary key (user_id, athlete_id)
);

alter table public.message_views enable row level security;

create policy "message_views_own" on public.message_views for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
