-- Workout Templates: reusable exercise bundles a user builds once and
-- assigns to any athlete they have access to. User-owned, NOT athlete-scoped
-- - a deliberate departure from every other table in this app, which is all
-- athlete-scoped. Safe to re-run from scratch (every step is guarded).

-- ============================================================
-- exercises: suggested per-exercise defaults. These ONLY pre-fill the form
-- whenever an exercise is added to ANY template (new or existing) - never
-- overwritten by what a specific template saves (see workout_template_exercises).
-- ============================================================
alter table public.exercises add column if not exists default_sets int;
alter table public.exercises add column if not exists default_reps int;
alter table public.exercises add column if not exists default_weight numeric;
alter table public.exercises add column if not exists default_duration_seconds int;
alter table public.exercises add column if not exists default_distance numeric;
alter table public.exercises add column if not exists default_intensity text;

-- ============================================================
-- workout_templates: owned by the creating user account, not an athlete.
-- created_by null + is_preset true = a shipped default, shared/global.
-- ============================================================
create table if not exists public.workout_templates (
  id bigint generated by default as identity primary key,
  created_by uuid references auth.users(id),
  is_preset boolean not null default false,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

alter table public.workout_templates enable row level security;

-- ============================================================
-- workout_template_hidden_for_user: per-user "hide this preset from my
-- list" - never a real delete on the shared preset row. Created here,
-- before workout_templates' own policies, because those policies reference
-- this table (a policy can't reference a table that doesn't exist yet).
-- ============================================================
create table if not exists public.workout_template_hidden_for_user (
  user_id uuid not null references auth.users(id),
  template_id bigint not null references public.workout_templates(id) on delete cascade,
  primary key (user_id, template_id)
);

alter table public.workout_template_hidden_for_user enable row level security;

drop policy if exists "workout_template_hidden_for_user_all" on public.workout_template_hidden_for_user;
create policy "workout_template_hidden_for_user_all" on public.workout_template_hidden_for_user for all using (
  user_id = auth.uid()
) with check (
  user_id = auth.uid()
);

drop policy if exists "workout_templates_select" on public.workout_templates;
create policy "workout_templates_select" on public.workout_templates for select using (
  (
    is_preset = true
    and not exists (
      select 1 from public.workout_template_hidden_for_user h
      where h.template_id = workout_templates.id and h.user_id = auth.uid()
    )
  )
  or created_by = auth.uid()
);

drop policy if exists "workout_templates_insert" on public.workout_templates;
create policy "workout_templates_insert" on public.workout_templates for insert with check (
  created_by = auth.uid() and is_preset = false
);

drop policy if exists "workout_templates_update" on public.workout_templates;
create policy "workout_templates_update" on public.workout_templates for update using (
  created_by = auth.uid()
) with check (
  created_by = auth.uid() and is_preset = false
);

drop policy if exists "workout_templates_delete" on public.workout_templates;
create policy "workout_templates_delete" on public.workout_templates for delete using (
  created_by = auth.uid()
);

-- A user cannot have two visible templates with the same name. Presets
-- (created_by is null) are excluded here - a straight unique constraint on
-- name alone would wrongly stop two different users both naming something
-- "Leg Day". Colliding with a still-visible preset name is checked in the app.
drop index if exists workout_templates_owner_name_idx;
create unique index workout_templates_owner_name_idx on public.workout_templates (created_by, name) where created_by is not null;

-- ============================================================
-- workout_template_exercises: what THIS template actually saved for this
-- exercise - independent of exercises.default_* and of every other template.
-- ============================================================
create table if not exists public.workout_template_exercises (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.workout_templates(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id),
  order_index int not null default 0,
  default_sets int,
  default_reps int,
  default_weight numeric,
  default_duration_seconds int,
  default_distance numeric,
  default_intensity text
);

alter table public.workout_template_exercises enable row level security;

drop policy if exists "workout_template_exercises_select" on public.workout_template_exercises;
create policy "workout_template_exercises_select" on public.workout_template_exercises for select using (
  exists (
    select 1 from public.workout_templates t
    where t.id = workout_template_exercises.template_id
      and (
        (
          t.is_preset = true
          and not exists (
            select 1 from public.workout_template_hidden_for_user h
            where h.template_id = t.id and h.user_id = auth.uid()
          )
        )
        or t.created_by = auth.uid()
      )
  )
);

-- Write access requires OWNING the template - editing a preset's exercises
-- directly is never allowed; the app forks a new template first (see spec).
drop policy if exists "workout_template_exercises_write" on public.workout_template_exercises;
create policy "workout_template_exercises_write" on public.workout_template_exercises for all using (
  exists (
    select 1 from public.workout_templates t
    where t.id = workout_template_exercises.template_id and t.created_by = auth.uid()
  )
) with check (
  exists (
    select 1 from public.workout_templates t
    where t.id = workout_template_exercises.template_id and t.created_by = auth.uid()
  )
);

-- ============================================================
-- workouts: link back to the template a workout was started from, if any.
-- A one-time copy at assignment time (see app) - never a live reference,
-- so editing/completing a workout never changes the template it came from.
-- ============================================================
alter table public.workouts add column if not exists template_id bigint references public.workout_templates(id);

-- ============================================================
-- Fix distance_unit for throwing drills authored in feet, not yards -
-- the earlier category-based guess (all Throwing -> yd) was wrong for
-- these; the coach-authored defaults below are in feet.
-- ============================================================

update public.exercises set distance_unit = 'ft' where name = 'Easy Catch';
update public.exercises set distance_unit = 'ft' where name = 'Long Toss';
update public.exercises set distance_unit = 'ft' where name = 'Flat-Ground Throwing';
update public.exercises set distance_unit = 'ft' where name = 'Weighted-Ball Throwing';

-- ============================================================
-- Suggested per-exercise defaults on the library itself - used ONLY
-- to pre-fill the form whenever an exercise is added to ANY template
-- (new or existing). Never overwritten by what a template saves.
-- Distance ranges/text in the source spreadsheet ("30-45 ft") were
-- reduced to the low end as a single conservative starting number.
-- ============================================================

update public.exercises set
  default_sets = 3,
  default_reps = 12,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Goblet Squat';

update public.exercises set
  default_sets = 4,
  default_reps = 6,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'Moderate-High'
where name = 'Back Squat';

update public.exercises set
  default_sets = 4,
  default_reps = 6,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'Moderate-High'
where name = 'Front Squat';

update public.exercises set
  default_sets = 3,
  default_reps = 8,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Romanian Deadlift';

update public.exercises set
  default_sets = 4,
  default_reps = 5,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'Moderate-High'
where name = 'Trap-Bar Deadlift';

update public.exercises set
  default_sets = 3,
  default_reps = 8,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Bulgarian Split Squat';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Reverse Lunge';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Lateral Lunge';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Step-Ups';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Hip Thrust';

update public.exercises set
  default_sets = 3,
  default_reps = 12,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Glute Bridge';

update public.exercises set
  default_sets = 3,
  default_reps = 15,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Calf Raises';

update public.exercises set
  default_sets = 3,
  default_reps = 8,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Dumbbell Bench Press';

update public.exercises set
  default_sets = 3,
  default_reps = 8,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Incline Dumbbell Press';

update public.exercises set
  default_sets = 3,
  default_reps = 12,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Push-Ups';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'One-Arm DB Row';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Seated Cable Row';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Lat Pulldown';

update public.exercises set
  default_sets = 3,
  default_reps = 6,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Pull-Ups';

update public.exercises set
  default_sets = 3,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 30,
  default_distance = 40,
  default_intensity = null
where name = 'Farmer Carry';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Dead Bug';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Bird Dog';

update public.exercises set
  default_sets = 3,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 30,
  default_distance = null,
  default_intensity = null
where name = 'Plank';

update public.exercises set
  default_sets = 3,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 20,
  default_distance = null,
  default_intensity = null
where name = 'Side Plank';

update public.exercises set
  default_sets = 3,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Pallof Press';

update public.exercises set
  default_sets = 3,
  default_reps = 15,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Russian Twist';

update public.exercises set
  default_sets = 3,
  default_reps = 6,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'High'
where name = 'Med-Ball Rotational Throw';

update public.exercises set
  default_sets = 3,
  default_reps = 6,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'High'
where name = 'Med-Ball Scoop Toss';

update public.exercises set
  default_sets = 3,
  default_reps = 6,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'High'
where name = 'Med-Ball Slam';

update public.exercises set
  default_sets = 3,
  default_reps = 5,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'High'
where name = 'Box Jump';

update public.exercises set
  default_sets = 3,
  default_reps = 5,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'High'
where name = 'Broad Jump';

update public.exercises set
  default_sets = 3,
  default_reps = 6,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'High'
where name = 'Lateral Bounds';

update public.exercises set
  default_sets = 2,
  default_reps = 15,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Band External Rotation';

update public.exercises set
  default_sets = 2,
  default_reps = 15,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Band Internal Rotation';

update public.exercises set
  default_sets = 2,
  default_reps = 15,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Band Pull-Aparts';

update public.exercises set
  default_sets = 2,
  default_reps = 15,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Band Face Pull';

update public.exercises set
  default_sets = 2,
  default_reps = 15,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Band Row';

update public.exercises set
  default_sets = 2,
  default_reps = 12,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Scapular Push-Ups';

update public.exercises set
  default_sets = 2,
  default_reps = 15,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Wrist Curls';

update public.exercises set
  default_sets = 2,
  default_reps = 15,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Reverse Wrist Curls';

update public.exercises set
  default_sets = 2,
  default_reps = 12,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Pronation/Supination';

update public.exercises set
  default_sets = null,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 300,
  default_distance = 30,
  default_intensity = 'Low'
where name = 'Easy Catch';

update public.exercises set
  default_sets = null,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 600,
  default_distance = 90,
  default_intensity = 'Moderate-High'
where name = 'Long Toss';

update public.exercises set
  default_sets = 1,
  default_reps = 20,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = 60,
  default_intensity = 'Moderate'
where name = 'Flat-Ground Throwing';

update public.exercises set
  default_sets = null,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Bullpen';

update public.exercises set
  default_sets = null,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Pitching Mechanics Drill';

update public.exercises set
  default_sets = 1,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = 45,
  default_intensity = 'Moderate'
where name = 'Weighted-Ball Throwing';

update public.exercises set
  default_sets = 1,
  default_reps = 5,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = 10,
  default_intensity = 'Max'
where name = 'Sprint - 10 yd';

update public.exercises set
  default_sets = 1,
  default_reps = 5,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = 20,
  default_intensity = 'Max'
where name = 'Sprint - 20 yd';

update public.exercises set
  default_sets = 1,
  default_reps = 4,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = 30,
  default_intensity = 'Max'
where name = 'Sprint - 30 yd';

update public.exercises set
  default_sets = 3,
  default_reps = 4,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = 60,
  default_intensity = 'High'
where name = 'Shuttle Run';

update public.exercises set
  default_sets = 3,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 20,
  default_distance = 20,
  default_intensity = 'Moderate-High'
where name = 'Lateral Shuffle';

update public.exercises set
  default_sets = null,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 900,
  default_distance = null,
  default_intensity = 'Moderate'
where name = 'Bike';

update public.exercises set
  default_sets = null,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 1200,
  default_distance = 1,
  default_intensity = 'Moderate'
where name = 'Jog/Run';

update public.exercises set
  default_sets = null,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 1200,
  default_distance = null,
  default_intensity = 'Low-Moderate'
where name = 'Incline Walk';

update public.exercises set
  default_sets = null,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 900,
  default_distance = null,
  default_intensity = 'Moderate'
where name = 'Elliptical';

update public.exercises set
  default_sets = 3,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = 'Moderate'
where name = 'Jump Rope';

update public.exercises set
  default_sets = 2,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 30,
  default_distance = null,
  default_intensity = null
where name = 'Hip Flexor Stretch';

update public.exercises set
  default_sets = 2,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 30,
  default_distance = null,
  default_intensity = null
where name = 'Hamstring Stretch';

update public.exercises set
  default_sets = 2,
  default_reps = null,
  default_weight = null,
  default_duration_seconds = 30,
  default_distance = null,
  default_intensity = null
where name = 'Shoulder Stretch';

update public.exercises set
  default_sets = 2,
  default_reps = 10,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'Thoracic Rotation';

update public.exercises set
  default_sets = 2,
  default_reps = 6,
  default_weight = null,
  default_duration_seconds = null,
  default_distance = null,
  default_intensity = null
where name = 'World''s Greatest Stretch';

-- ============================================================
-- Preset templates (is_preset = true, created_by = null) - global,
-- shared, visible to everyone by default. Guarded so re-running this
-- file doesn't create duplicates.
-- ============================================================

do $$
declare
  v_template_id bigint;
begin
  if not exists (select 1 from public.workout_templates where name = 'Arm Care Day' and is_preset = true) then
    insert into public.workout_templates (name, description, is_preset, created_by)
    values ('Arm Care Day', 'Starting suggestions only - adjust sets/reps/weight for your athlete.', true, null)
    returning id into v_template_id;

    insert into public.workout_template_exercises
      (template_id, exercise_id, order_index, default_sets, default_reps, default_weight, default_duration_seconds, default_distance, default_intensity)
    values
      (v_template_id, (select id from public.exercises where name = 'Band External Rotation'), 0, 2, 15, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Band Internal Rotation'), 1, 2, 15, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Band Pull-Aparts'), 2, 2, 15, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Band Face Pull'), 3, 2, 15, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Band Row'), 4, 2, 15, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Scapular Push-Ups'), 5, 2, 12, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Wrist Curls'), 6, 2, 15, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Reverse Wrist Curls'), 7, 2, 15, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Pronation/Supination'), 8, 2, 12, null, null, null, null);
  end if;
end $$;

do $$
declare
  v_template_id bigint;
begin
  if not exists (select 1 from public.workout_templates where name = 'Lower Body Strength' and is_preset = true) then
    insert into public.workout_templates (name, description, is_preset, created_by)
    values ('Lower Body Strength', 'Starting suggestions only - adjust sets/reps/weight for your athlete.', true, null)
    returning id into v_template_id;

    insert into public.workout_template_exercises
      (template_id, exercise_id, order_index, default_sets, default_reps, default_weight, default_duration_seconds, default_distance, default_intensity)
    values
      (v_template_id, (select id from public.exercises where name = 'Goblet Squat'), 0, 3, 12, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Back Squat'), 1, 4, 6, null, null, null, 'Moderate-High'),
      (v_template_id, (select id from public.exercises where name = 'Front Squat'), 2, 4, 6, null, null, null, 'Moderate-High'),
      (v_template_id, (select id from public.exercises where name = 'Romanian Deadlift'), 3, 3, 8, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Trap-Bar Deadlift'), 4, 4, 5, null, null, null, 'Moderate-High'),
      (v_template_id, (select id from public.exercises where name = 'Bulgarian Split Squat'), 5, 3, 8, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Reverse Lunge'), 6, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Lateral Lunge'), 7, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Step-Ups'), 8, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Hip Thrust'), 9, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Glute Bridge'), 10, 3, 12, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Calf Raises'), 11, 3, 15, null, null, null, null);
  end if;
end $$;

do $$
declare
  v_template_id bigint;
begin
  if not exists (select 1 from public.workout_templates where name = 'Upper Body Strength' and is_preset = true) then
    insert into public.workout_templates (name, description, is_preset, created_by)
    values ('Upper Body Strength', 'Starting suggestions only - adjust sets/reps/weight for your athlete.', true, null)
    returning id into v_template_id;

    insert into public.workout_template_exercises
      (template_id, exercise_id, order_index, default_sets, default_reps, default_weight, default_duration_seconds, default_distance, default_intensity)
    values
      (v_template_id, (select id from public.exercises where name = 'Dumbbell Bench Press'), 0, 3, 8, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Incline Dumbbell Press'), 1, 3, 8, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Push-Ups'), 2, 3, 12, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'One-Arm DB Row'), 3, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Seated Cable Row'), 4, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Lat Pulldown'), 5, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Pull-Ups'), 6, 3, 6, null, null, null, null);
  end if;
end $$;

do $$
declare
  v_template_id bigint;
begin
  if not exists (select 1 from public.workout_templates where name = 'Core' and is_preset = true) then
    insert into public.workout_templates (name, description, is_preset, created_by)
    values ('Core', 'Starting suggestions only - adjust sets/reps/weight for your athlete.', true, null)
    returning id into v_template_id;

    insert into public.workout_template_exercises
      (template_id, exercise_id, order_index, default_sets, default_reps, default_weight, default_duration_seconds, default_distance, default_intensity)
    values
      (v_template_id, (select id from public.exercises where name = 'Farmer Carry'), 0, 3, null, null, 30, 40, null),
      (v_template_id, (select id from public.exercises where name = 'Dead Bug'), 1, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Bird Dog'), 2, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Plank'), 3, 3, null, null, 30, null, null),
      (v_template_id, (select id from public.exercises where name = 'Side Plank'), 4, 3, null, null, 20, null, null),
      (v_template_id, (select id from public.exercises where name = 'Pallof Press'), 5, 3, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'Russian Twist'), 6, 3, 15, null, null, null, null);
  end if;
end $$;

do $$
declare
  v_template_id bigint;
begin
  if not exists (select 1 from public.workout_templates where name = 'Power/Explosiveness' and is_preset = true) then
    insert into public.workout_templates (name, description, is_preset, created_by)
    values ('Power/Explosiveness', 'Starting suggestions only - adjust sets/reps/weight for your athlete.', true, null)
    returning id into v_template_id;

    insert into public.workout_template_exercises
      (template_id, exercise_id, order_index, default_sets, default_reps, default_weight, default_duration_seconds, default_distance, default_intensity)
    values
      (v_template_id, (select id from public.exercises where name = 'Med-Ball Rotational Throw'), 0, 3, 6, null, null, null, 'High'),
      (v_template_id, (select id from public.exercises where name = 'Med-Ball Scoop Toss'), 1, 3, 6, null, null, null, 'High'),
      (v_template_id, (select id from public.exercises where name = 'Med-Ball Slam'), 2, 3, 6, null, null, null, 'High'),
      (v_template_id, (select id from public.exercises where name = 'Box Jump'), 3, 3, 5, null, null, null, 'High'),
      (v_template_id, (select id from public.exercises where name = 'Broad Jump'), 4, 3, 5, null, null, null, 'High'),
      (v_template_id, (select id from public.exercises where name = 'Lateral Bounds'), 5, 3, 6, null, null, null, 'High');
  end if;
end $$;

do $$
declare
  v_template_id bigint;
begin
  if not exists (select 1 from public.workout_templates where name = 'Throwing Progression' and is_preset = true) then
    insert into public.workout_templates (name, description, is_preset, created_by)
    values ('Throwing Progression', 'Starting suggestions only - adjust sets/reps/weight for your athlete.', true, null)
    returning id into v_template_id;

    insert into public.workout_template_exercises
      (template_id, exercise_id, order_index, default_sets, default_reps, default_weight, default_duration_seconds, default_distance, default_intensity)
    values
      (v_template_id, (select id from public.exercises where name = 'Easy Catch'), 0, null, null, null, 300, 30, 'Low'),
      (v_template_id, (select id from public.exercises where name = 'Long Toss'), 1, null, null, null, 600, 90, 'Moderate-High'),
      (v_template_id, (select id from public.exercises where name = 'Flat-Ground Throwing'), 2, 1, 20, null, null, 60, 'Moderate'),
      (v_template_id, (select id from public.exercises where name = 'Weighted-Ball Throwing'), 3, 1, 10, null, null, 45, 'Moderate');
  end if;
end $$;

do $$
declare
  v_template_id bigint;
begin
  if not exists (select 1 from public.workout_templates where name = 'Speed & Conditioning' and is_preset = true) then
    insert into public.workout_templates (name, description, is_preset, created_by)
    values ('Speed & Conditioning', 'Starting suggestions only - adjust sets/reps/weight for your athlete.', true, null)
    returning id into v_template_id;

    insert into public.workout_template_exercises
      (template_id, exercise_id, order_index, default_sets, default_reps, default_weight, default_duration_seconds, default_distance, default_intensity)
    values
      (v_template_id, (select id from public.exercises where name = 'Sprint - 10 yd'), 0, 1, 5, null, null, 10, 'Max'),
      (v_template_id, (select id from public.exercises where name = 'Sprint - 20 yd'), 1, 1, 5, null, null, 20, 'Max'),
      (v_template_id, (select id from public.exercises where name = 'Sprint - 30 yd'), 2, 1, 4, null, null, 30, 'Max'),
      (v_template_id, (select id from public.exercises where name = 'Shuttle Run'), 3, 3, 4, null, null, 60, 'High'),
      (v_template_id, (select id from public.exercises where name = 'Lateral Shuffle'), 4, 3, null, null, 20, 20, 'Moderate-High'),
      (v_template_id, (select id from public.exercises where name = 'Bike'), 5, null, null, null, 900, null, 'Moderate'),
      (v_template_id, (select id from public.exercises where name = 'Jog/Run'), 6, null, null, null, 1200, 1, 'Moderate'),
      (v_template_id, (select id from public.exercises where name = 'Incline Walk'), 7, null, null, null, 1200, null, 'Low-Moderate'),
      (v_template_id, (select id from public.exercises where name = 'Elliptical'), 8, null, null, null, 900, null, 'Moderate'),
      (v_template_id, (select id from public.exercises where name = 'Jump Rope'), 9, 3, null, null, null, null, 'Moderate');
  end if;
end $$;

do $$
declare
  v_template_id bigint;
begin
  if not exists (select 1 from public.workout_templates where name = 'Mobility/Recovery' and is_preset = true) then
    insert into public.workout_templates (name, description, is_preset, created_by)
    values ('Mobility/Recovery', 'Starting suggestions only - adjust sets/reps/weight for your athlete.', true, null)
    returning id into v_template_id;

    insert into public.workout_template_exercises
      (template_id, exercise_id, order_index, default_sets, default_reps, default_weight, default_duration_seconds, default_distance, default_intensity)
    values
      (v_template_id, (select id from public.exercises where name = 'Hip Flexor Stretch'), 0, 2, null, null, 30, null, null),
      (v_template_id, (select id from public.exercises where name = 'Hamstring Stretch'), 1, 2, null, null, 30, null, null),
      (v_template_id, (select id from public.exercises where name = 'Shoulder Stretch'), 2, 2, null, null, 30, null, null),
      (v_template_id, (select id from public.exercises where name = 'Thoracic Rotation'), 3, 2, 10, null, null, null, null),
      (v_template_id, (select id from public.exercises where name = 'World''s Greatest Stretch'), 4, 2, 6, null, null, null, null);
  end if;
end $$;
